### ISSUE TITLE
Call endpoint: Support to send XML or Json file

### ISSUE THREAD

**Issue by diethardsteiner** [pentaho/pdi-platform-utils-plugin#1]
In some cases, in example to change the user password, we have to send an XML or Json file to the server. Can you please add support for this to the 'Call endpoint' step?

**Comment by bluezio** [comment]
Was this added in the end? I've just run against this today on Pentaho 5.4.0.1.

**Comment by pamval** [comment]
I don't think it was. Please create an improvement jira at jira.pentaho.com so we can track this down appropriately.

**Comment by bluezio** [comment]
I've reported the issue here: http://jira.pentaho.com/browse/PDI-14687.
